"""Common disclaimer phrases used across the project."""

STRICTLY_SOCIAL_MEDIA = "STRICTLY A SOCIAL MEDIA PLATFORM"
INTELLECTUAL_PROPERTY_ARTISTIC_INSPIRATION = "Intellectual Property & Artistic Inspiration"
LEGAL_ETHICAL_SAFEGUARDS = "Legal & Ethical Safeguards"

__all__ = [
    "STRICTLY_SOCIAL_MEDIA",
    "INTELLECTUAL_PROPERTY_ARTISTIC_INSPIRATION",
    "LEGAL_ETHICAL_SAFEGUARDS",
]
